### ISSUE TITLE
Stop it!!

### ISSUE THREAD

**Issue by G9-dev-real** [clazarow1/clazarow1.github.io#10]
Fards at @clazarow1

**Comment by G9-dev-real** [comment]
THAT'S IT I GONNA UNWATCH CLAZAROW1'S REPOS AND DISLIKE ALL HIS VIDEOS AND I GONNA EXPOSE HIS VOICE

**Comment by clazarow1** [comment]
I'm getting tired of your bullshit. I'm not fucking around with you, kid. You're trying to get me off the platform, whenever I'm already OVER the age of consent for most SOCIAL MEDIA platforms, including this one. What do I do? Nothing. I'm fine by my current state. You should GET THE FUCK OFF this platform and NEVER return until you're dead. Fuck off.

**Comment by G9-dev-real** [comment]
These are with lot of bad words

**Comment by G9-dev-real** [comment]
I'm not dead

**Comment by G9-dev-real** [comment]
C*le* Laza**w. Stop it.
