### ISSUE TITLE
Honestly.

### ISSUE THREAD

**Issue by clazarow1** [clazarow1/clazarow1.github.io#13]
If you want to talk to me, don't be like G9-dev-real, they're a child that doesn't give a fuck about life. Don't be like them, you'll end up getting reported and will get all your accounts deleted.

**Comment by Darik2121** [comment]
> If you want to talk to me, don't be like G9-dev-real, they're a child that doesn't give a f**k about life. Don't be like them, you'll end up getting reported and will get all your accounts deleted.

G9-dev-real's account wont be deleted

**Comment by Darik2121** [comment]
blah blah


![Dramatic_Chipmunk](https://user-images.githubusercontent.com/109795595/181828772-6ddc71dd-f03f-44d4-83ec-918ca33a5d4d.png)
this you @clazarow1

**Comment by clazarow1** [comment]
> blah blah
> 
> 
> ![Dramatic_Chipmunk](https://user-images.githubusercontent.com/109795595/181828772-6ddc71dd-f03f-44d4-83ec-918ca33a5d4d.png)
> this you @clazarow1 

Same rules apply to you as well!

**Comment by Darik2121** [comment]
nope

**Comment by Darik2121** [comment]
my account won't be deleted

**Comment by clazarow1** [comment]
> my account won't be deleted



Just for the record, you have been reported, alongside G9-Dev-real. You will get your accounts deleted by the GitHub team and don't come back. You're welcome!

**Comment by Darik2121** [comment]
> > my account won't be deleted
> 
> Just for the record, you have been reported, alongside G9-Dev-real. You will get your accounts deleted by the GitHub team and don't come back. You're welcome!

kindly, no.

**Comment by clazarow1** [comment]
Good luck, do not come back here again fucker. Get a job, get a life, and most of all, GO TOUCH A LOT OF FUCKING GRASS.

**Comment by Darik2121** [comment]
no

**Comment by Darik2121** [comment]
I've said that I made my account because I was bored

**Comment by Endermanch-real123** [comment]
> Good luck, do not come back here again fucker. Get a job, get a life, and most of all, GO TOUCH A LOT OF FUCKING GRASS.

BAD WORD!!!
DELETE THAT NOW!!!1

**Comment by clazarow1** [comment]
Look, dumbfuck. I want your IP banned on this platform. You are one son of a bitch that wants life your way. Shut the fuck up, and delete all the accounts that you have that are active. Touch a lot of fucking grass, asshole.

**Comment by clazarow1** [comment]
Also, this is your final warning before I ask for you to get your IP banned. I will ask them to report it.

**Comment by clazarow1** [comment]
@Endermanch-real123

**Comment by Endermanch-real123** [comment]
> Also, this is your final warning before I ask for you to get your IP banned. I will ask them to report it.

THEN IM GOING TO DESTROY YOU

I DONT WANT MY IP BANNED IN THIS PLATFORM

**Comment by Endermanch-real123** [comment]
> Also, this is your final warning before I ask for you to get your IP banned. I will ask them to report it.

no you cant

**Comment by Endermanch-real123** [comment]
caleb im sorry  forgive me

**Comment by clazarow1** [comment]
Look, I understand. You're a child, you shouldn't be on here anyway. Please stop impersonating accounts by creating "-real..." at the end of the username. Also, that will result in an account ban.

**Comment by clazarow1** [comment]
If you want to play it safe, please delete this account and g9-dev-real. I'm not a mod on GitHub or anything, but I'm literally trying to abide by the rules of any platform.

**Comment by Darik8Coder** [comment]
no i wont

**Comment by Darik8Coder** [comment]
STOP REPORTING US >:(
