### ISSUE TITLE
I won't delete my account!!

### ISSUE THREAD

**Issue by Darik2121** [clazarow1/clazarow1.github.io#14]
THE ANSWER WAS IS AND ALWAYS BE NO!!

**Comment by Darik2121** [comment]
wow! i've been having fun! :D please delete your account that you made and NEVER COME HERE AGAIN.

**Comment by clazarow1** [comment]
Look, dumbass. I don't give a fuck on what you say, you'll be reported as well as G9-Dev-Real. Rules are rules, you are underage and shut the fuck up.
