### ISSUE TITLE
Also, this is your final warning before I ask for you to get your IP banned. I will ask them to report it.

### ISSUE THREAD

**Issue by Endermanch-real123** [clazarow1/clazarow1.github.io#15]
DONT DO IT im sorry

**Comment by Endermanch-real123** [comment]
pls forgive me.

**Comment by clazarow1** [comment]
Look, I understand. You're a child, you shouldn't be on here anyway. Please stop impersonating accounts by creating "-real..." at the end of the username. Also, that will result in an account ban. If you want to play it safe, please delete this account and g9-dev-real. I'm not a mod on GitHub or anything, but I'm literally trying to abide by the rules of any platform.

**Comment by Darik8Coder** [comment]
> Reference in new

nah im not deleting
