### ISSUE TITLE
No

### ISSUE THREAD

**Issue by G9-dev-real** [clazarow1/clazarow1.github.io#2]
Darik is 8 years old not 70 years old, don't make him report you.

**Comment by clazarow1** [comment]
Look, people under the age of 13 are PROHIBITED from using this site (and anywhere). If you want to counter-argue why kids under the age of 13 should be allowed to be on all sites, there aren't any VALID reasons. You're a child and please stop using this site as a whole until you've at least been 70 years old. That's how much I don't want little kids to be on this site. Please delete all accounts that you made on here and don't come here again.
