### ISSUE TITLE
THE ANSWER ALWAYS WILL BE YES

### ISSUE THREAD

**Issue by Darik2121** [clazarow1/clazarow1.github.io#6]
G9-DEV REAL WILL!!

**Comment by clazarow1** [comment]
I'm having too much fun with this. Last warning or I will report ALL your accounts for:

1. Spamming other repositories

2. Being underage and acting like a little spoiled brats that doesn't give a fuck about life

3. Threatening to DDOS Andrew

**Comment by G9-dev-real** [comment]
> G9-DEV REAL WILL!!

He didn't say that!!!

**Comment by G9-dev-real** [comment]
Im kinda tired of looking at this, just stop talking here...

**Comment by Darik2121** [comment]
> I'm having too much fun with this. Last warning or I will report ALL your accounts for:
> 
> 1. Spamming other repositories
> 2. Being underage and acting like a little spoiled brats that doesn't give a f**k about life
> 3. Threatening to DDOS Andrew

thats a bad word

**Comment by G9-dev-real** [comment]
RICKROLL CLABE
