### ISSUE TITLE
NO!!

### ISSUE THREAD

**Issue by G9-dev-real** [clazarow1/clazarow1.github.io#8]
I'VE SAID THAT I WONT DELETE THE ACCOUNTS DONT MAKE ME REPORT YOU!!!

**Comment by clazarow1** [comment]
Oh, little spoiled brat. You're WAAAAAAAAAAY under the age of consent. You threatened to DDOS someone by IP address. What else is there to prove?

**Comment by G9-dev-real** [comment]
> Oh, little spoiled brat. You're WAAAAAAAAAAY under the age of consent. You threatened to DDOS someone by IP address. What else is there to prove?



> Oh, little spoiled brat. You're WAAAAAAAAAAY under the age of consent. You threatened to DDOS someone by IP address. What else is there to prove?

I don't DDOS someone
